name: 'Install and update MikTeX'
runs:
  using: 'composite'
  steps:
    - name: Install MikTeX
      shell: bash
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
        echo "deb http://miktex.org/download/ubuntu noble universe" | sudo tee /etc/apt/sources.list.d/miktex.list
        sudo apt update
        sudo apt install miktex
        echo Installed MikTeX

    - name: Configure MikTeX
      shell: bash
      run: |
        sudo miktexsetup --shared=yes finish 
        sudo initexmf --admin --set-config-value [MPM]AutoInstall=1
        echo Inited MikTeX

    - name: Update MikTeX (admin)
      shell: bash
      run: |
        sudo mpm --admin --find-updates
        sudo mpm --admin --update

    - name: Update MikTeX (user)
      shell: bash
      run: |
        mpm --find-updates
        mpm --update
