name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - uses: CatInCosmicSpace/latex-template/actions/miktex@master

      - name: Compile full example
        run: |
          initexmf --register-root $PWD
          cd ./full-example
          latexmk -pdf main.tex

      - name: Clean after build full example
        run: |
          cd ./full-example
          latexmk -c ./main.tex

      - name: "Git artifact: PDF"
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            ./full-example/main.pdf
