name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install MikTeX
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
          echo "deb http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt update
          sudo apt install miktex
          echo Installed MikTeX

      - name: Configure MikTeX
        run: |
          sudo miktexsetup --shared=yes finish 
          sudo initexmf --admin --set-config-value [MPM]AutoInstall=1
          echo Inited MikTeX

      - name: Update MikTeX
        run: |
          sudo mpm --find-updates
          sudo mpm --update

      - name: Compile document
        run: |
          initexmf --register-root $PWD
          cd ./example
          latexmk -pdf main.tex

      - name: Clean after build
        run: |
          cd ./example
          latexmk -c ./main.tex

      - name: Compile example
        run: |
          cd ./tex/latex/bmstu-iu8
          latexmk -pdf bmstu-example.tex
          latexmk -c ./bmstu-example.tex

      - name: ls tex dir
        run: |
          ls -lah .

      - name: Zip files
        run: |
          cd ./tex/latex/bmstu-iu8
          zip -r bmstu-iu8.zip ./tex

      - name: Git artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            ./example/main.pdf
            ./bmstu-iu8.zip
