name: CTAN

on:
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Get tag'
        run: |
          echo "GIT_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - uses: CatInCosmicSpace/latex-template/actions/miktex@master

      - name: Compile minimal example
        run: |
          initexmf --register-root $PWD
          cd ./example
          latexmk -pdf bmstu-example.tex
      
      - name: Clean after build minimal example
        run: |
          cd ./example
          latexmk -c ./bmstu-example.tex

      - name: Make CTAN package
        run: |
          mkdir bmstu-iu8
          cp -r ./tex/latex/bmstu-iu8 ./bmstu-iu8/
          cp -r ./example/* ./bmstu-iu8/
          rm -rf ./bmstu-iu8/bmstu-example.bbl

      - name: Zip files
        run: |
          zip -r bmstu-iu8.zip ./bmstu-iu8/
      
      - name: "Git artifact: CTAN zip"
        uses: actions/upload-artifact@v4
        with:
          name: CTAN zip
          path: |
            ./bmstu-iu8.zip

      - name: "Remove bmstu-iu8 directory"
        run: |
          rm -rf ./bmstu-iu8

      - name: "Upload to CTAN"
        uses: pgf-tikz/actions/ctan-upload@master
        with:
          action: upload
          author: 'CatInCosmicSpace'
          bugs: https://github.com/CatInCosmicSpace/latex-template/issues
          ctanPath: /macros/latex/contrib/bmstu-iu8
          email: catincosmicspace@gmail.com
          file: './bmstu-iu8.zip'
          home: https://github.com/CatInCosmicSpace/latex-template
          license: 'mit'
          pkg: "bmstu-iu8"
          repository: https://github.com/CatInCosmicSpace/latex-template
          summary: This package consist of a class file and style files for writing reports at the IU8 department of IU faculty of BMSTU.
          support: https://t.me/CatInCosmicSpace
          update: true
          uploader: github-actions
          version: ${{ env.GIT_TAG }}
